### ISSUE TITLE
Move item brings error message

### ISSUE THREAD

**Issue by jmizv** [dseph/EwsEditor#17]
Hi,
when I try to move an e-mail from one folder to another via the context menu "Move Item..." I get the following error. I tried with the option "Identify folder by unique id" and via selecting the folder via the option "Identify folder by well known name". The folder I wanted to move to was just freshly created. Is this a bug?

Regards

![ewseditor error](https://user-images.githubusercontent.com/37914724/49279622-467b1080-f488-11e8-8e8c-c79c7a37ffdb.jpg)

**Comment by dseph** [comment]
This should be fixed in 1.21
