### ISSUE TITLE
Errors Trying to Run After Downloading

### ISSUE THREAD

**Issue by matthewbordas** [dseph/EwsEditor#2]
I just downloaded the zip file, extracted it, and opened the `.sln` file in Visual Studio Enterprise 2017. I immediately tried to run it with a configuration of `Debug` and `Any CPU`, but was unable to due to the following errors shown in the Error List window:
<img width="1250" alt="ewseditorerrors" src="https://user-images.githubusercontent.com/7369954/31963416-6505cf32-b8b5-11e7-88e6-e71dc3676e06.PNG">

The project references look like this:
<img width="268" alt="ewseditormissingreferences" src="https://user-images.githubusercontent.com/7369954/31963519-ca2026b0-b8b5-11e7-91c7-0de139587a17.PNG">

NuGet says the following packages are installed (it ran a package restore when I initially tried to run the project):

- Microsoft.Bcl, version 1.1.10
- Microsoft.Bcl.Build, version 1.0.21
- Microsoft.IdentityModel.Clients.ActiveDirectory, version 3.17.0
- Microsoft.Net.Http, version 2.2.29
- System.Management.Automation.dll, version 10.0.10586

Am I missing something? I couldn't find a README with setup instructions.

Thanks!

**Comment by saurabha5** [comment]
I am also getting this same error on VS 2015 Enterprise and VS 2017 Professional.
However I did resolved the issue by updating the Nuget package for **"Microsoft.IdentityModel.Clients.ActiveDirectory" to 2.29.0**

Below is the `packages.config`

~~~ xml
<?xml version="1.0" encoding="utf-8"?>
<packages>
  <package id="Microsoft.Bcl" version="1.1.3" targetFramework="net45" />
  <package id="Microsoft.Bcl.Build" version="1.0.10" targetFramework="net45" />
  <package id="Microsoft.IdentityModel.Clients.ActiveDirectory" version="2.29.0" targetFramework="net451" />
  <package id="Microsoft.Net.Http" version="2.2.18" targetFramework="net45" />
  <package id="System.Management.Automation.dll" version="10.0.10586.0" targetFramework="net451" />
</packages>

~

**Comment by dseph** [comment]
Hello.  Did updating the components resolve the issue for you?
I just added a file called ToBuild.txt to EWSEditor - please check it out.

**Comment by rjk** [comment]
I had the same problem and updating the NuGet package to v2.29.0 worked for me. 

The project in github is referencing version 2.19.x which isn't available in the NuGet package manager Version dropdown. I guess this means that version isn't on NuGet anymore which is why the package restore doesn't work. In v3 of that package they removed the non-async methods so you can't just update to the latest package, which makes it a bit more confusing.

**Comment by dseph** [comment]
EWSEditor has no install.  It does have a requirement for the installed version of .NET.  Like any other program do not run it from a zip file.  There is now a readme.md file in the project which covers requirements and which NuGet packages need to be installed.
