### ISSUE TITLE
Unable to start exe on Windows 2016

### ISSUE THREAD

**Issue by hapklaar** [dseph/EwsEditor#20]
When I execute EWSEditor.exe as a domain user, which is local admin on the machine, nothing happens. In the Application eventlog I see event 5973 every time I try:

Activation of app Microsoft.Windows.Apprep.ChxApp_cw5n1h2txyewy!App failed with error: This app can't be activated by the Built-in Administrator. See the Microsoft-Windows-TWinUI/Operational log for additional information.

What could be the issue here?

**Comment by jschpp** [comment]
Windows seems to have disabled starting Apps as local Admin if the UAC is deactivated.
See this post on superuser: https://superuser.com/questions/699185/how-to-solve-error-this-app-cant-be-activated-by-the-built-in-administrator-in

**Comment by dseph** [comment]
Resolved by jschpp.  Closing.
