### ISSUE TITLE
Accept/decline

### ISSUE THREAD

**Issue by Sodininkas** [dseph/EwsEditor#3]
How I can using managed ews api access required attendies object, and modifier by hand he accepted or declined meeting. This task required for migration.

**Comment by dseph** [comment]
This is a very old question on the EWS Managed API - not EWSEditor.  You can pull the attendees list as properties (not MIME) from the calendar item. Run EWSEditor in Visual Studio.   Right click and edit a meeting in EWSEditor - you will see the attendees.  Next pause the running code in Visual Studio and see what it does.
