### ISSUE TITLE
Main window is cut off

### ISSUE THREAD

**Issue by dcormier** [dseph/EwsEditor#32]
Using the latest release binary ([1.21](https://github.com/dseph/EwsEditor/releases/tag/1.21)), the main window is cut off on the right side and is not resizable or scrollable.

![image](https://user-images.githubusercontent.com/216265/94144464-2677c680-fe3f-11ea-987d-bbed9d567842.png)

**Comment by YuriySamorodov** [comment]
Same issue here, but the window cuts off differently (not seeing OK button at all)
![image](https://user-images.githubusercontent.com/5260172/115631061-c92cf080-a30d-11eb-942a-8be49b54b550.png)

**Comment by dseph** [comment]
Hello. This is a known issue.  For now please try increasing the resolution of your screen.

**Comment by YuriySamorodov** [comment]
Thanks @desph! Well, it's kind of hard to increase display resolution in LCD screens era =)

**Comment by dseph** [comment]
I've made a few changes  and checked them in.  The login window and options window are rendering fine on my monitor set to 1024x768.  Please clone the code and build then test.  If there is an issue then please let me know what resolution you have set.
