### ISSUE TITLE
How do I install the tool?

### ISSUE THREAD

**Issue by chrischris2005** [dseph/EwsEditor#5]

**Comment by rjk** [comment]
See other comments below for compiled executable download.

To build it yourself, e.g. using MS Visual Studio: 

* Clone or download the GIT repository
* Open \EwsEditor\EwsEditor.sln file in Visual Studio 
* Build the solution. 
  * NB: Until Issue #2 is fixed you'll also need to update the NuGet package 'Microsoft.IdentityModel.Clients.ActiveDirectory' for it to compile. Updating to v3.X doesn't work though, it needs v2.X. I updated to the latest v2 which was 2.29.0. To do this: 
    * right-click on the EWSEditor project > Manage NuGet Packages
    * click 'Installed' at the top of the NuGet package manager if it's not already selected
    * click on 'Microsoft.IdentityModel.Clients.ActiveDirectory'
    * in the right-hand panel click on the Version dropdown and select 2.29.0 then click Update
    * now build the solution
* Run the solution or run the \EwsEditor\bin\Debug\EwsEditor.exe file

**Comment by poizan42** [comment]
Or just download it from https://github.com/dseph/EwsEditor/releases.

For earlier releases get the archive from https://archive.codeplex.com/?p=ewseditor. The releases are inside the zip file in the releases subdir. The numbered subfolders of that contains zip files (without the .zip extension) with guids as names (each folder contains a source and binary package). releaseList.json contains the mappings between the guids and the release names.

**Comment by poizan42** [comment]
@dseph Himself actually answered this on his blog: https://blogs.msdn.microsoft.com/webdav_101/2018/03/12/where-to-get-ewseditor/

**Comment by dseph** [comment]
There are build notes in the project.  You an also click on the "releases" link (has a price tag icon) and download the file ending with bin.zip.  Just unzip it to a folder on a local drive.
