### ISSUE TITLE
How  one can connect to o365 group mailbox?

### ISSUE THREAD

**Issue by sameerkattel** [dseph/EwsEditor#7]
I was trying to connect to group mailbox , created for MS team,  using a user(without mailbox) having applicationimpersonation privilege using impersonation but was not able to.
Can this be done using this tool?

**Comment by dseph** [comment]
Try setting the X-AnchorMailbox header to the smtp address of the mailbox being accessed.

Closing due to age.  Please open a new Issue if needed.
