### ISSUE TITLE
Calendar item properties not visible when viewing a Shared Calendar

### ISSUE THREAD

**Issue by cbraedley** [dseph/EwsEditor#8]
When opening a calendar item in my own mailbox, I am shown the individual calendar item properties.

If I open a calendar for someone who has made me an owner on their calendar, the properties don't load.  This used to work on 1.17.0.33450, but doesn't work on 1.18.1.29950 or 1.19.1.24286.

Steps to reproduce:
-Via Outlook, logged in as User2, add User1 as an owner on User2's Calendar
-Open EWSEditor as User1, and connect to User1's mailbox:
   -File | New Exchange Service...
   -Provide Autodiscover Email address of User1
   -Select appropriate EWS Schema Version (in my case, Exchange2010_SP2)
   -Click OK
-Click YES to add the mailbox root to the tree view
-Select the MsgFolderRoot folder
-Select Other | Find Appointments (CalendarView...)
-Click the "..." button
-Select the "Identify folder by well known name." radio button
-Select "Calendar" from the "Folder Name" drop down menu
-In the STMP Address field (spelling mistake on this page of the GUI) enter the email address for User2
-Click OK
-Select a Start Time and End Time that contains any calendar items
-Click OK
-In the new pop-up window, select any of the calendar items

It is at this point that I would expect the bottom pane to display the EWS item properties, but it is blank.  The EWSEditor.log file does contain the property values, so it is able to read them, it's just not displaying them.

Screenshot showing it broken:
![image](https://user-images.githubusercontent.com/36453044/36166269-4ea6b7b8-10c8-11e8-98ef-d8333c50fd1d.png)

Screenshot showing it working on earlier version:
![image](https://user-images.githubusercontent.com/36453044/36166168-162ea4fe-10c8-11e8-93a7-954d4ebb1bf5.png)

**Comment by dseph** [comment]
what happens if you set the x-anchormailbox to the one being accesed?

**Comment by cbraedley** [comment]
After some more testing, I found that the same behavior is present when doing the calendar search against the primary user's account.  (I'm not sure if that is the same as what you're asking or not.)

**Comment by dseph** [comment]
Thanks for letting me know.  I'll check into it.

**Comment by dseph** [comment]
The above behavior is odd and  I've not seen this issue before.  Its best to always have the x-anchormailbox header set when using EWS - even if you don't think you need it.  Existing code which works today may not work tomorrow without it.
